#!/usr/bin/env bash

if [ -n "$WWWUID" ]; then
  sed -i "s/user\ \=.*/user\ \= $WWWUID/g" /etc/php/8.0/fpm/pool.d/www.conf

  usermod -u $WWWUID ubuntu
fi

if [ ! -d /.composer ]; then
  mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ]; then
  exec gosu $WWWUID "$@"
else
  /usr/bin/supervisord
fi