version: "3"
services:
  app:
    build: ./docker/app
    dockerfile: Dockerfile
    image: CHANGEME
    ports:
      - 80
    volumes:
      - .:/var/www/html
    networks:
      - proxynet
      - appnet
      - mysqlnet
    labels:
      - "traefik.http.routers.CHANGME.rule=(Host(`DEV URL GOES HERE`))"
      - "traefik.http.routers.CHANGME-https.rule=(Host(`DEV URL GOES HERE`))"
      - "traefik.http.routers.CHANGME-https.entrypoints=https"
      - "traefik.http.routers.CHANGME-https.tls=true"
      - "traefik.http.routers.CHANGME-https.tls.domains[0].main=DEV URL GOES HERE"
      - "traefik.docker.network=proxy-net"
  redis:
    image: redis:alpine
    networks:
      - appnet
networks:
  appnet:
    driver: bridge
  proxynet:
    external:
      name: proxy-net
  mysqlnet:
    external:
      name: mysql-net
